# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 81ee06d2f5740f8a04a681b523904b809b7dabbe524afa28a2975f79248af0c27a5c0d5bfc1719d550c4556e60d0276a013b1712e95af434f4c858f47a211ab4

test:
  secret_key_base: 7f86902cfe1ac5e585e89eec54d5192cb82b6540116ae3685fea9e597ba759050d799b4875c338f0d8bbf2c8f9d1b844f4d3ae38ad9fecae6a3d6c765937270e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
